# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 527fcb3f02dba1f7ce2fa5c63a557fb07216ae473bbb52f9a914fa983e0be5e10f3f3dde047055bf5abd8092f1a3c9b9b358362a5e9b77419b9b5d8b6d27c0b2

test:
  secret_key_base: 23f8de5dd536b5aefe224a58aae0be28763e52ea6da249f333c4401cf18dfd9f177bb32c4080fcbdbcb733c49a858186703eff1d73284d5bfb69a6514a23d1f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
